name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      #      - name: tests should run here!
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_G }}
          username: oauth
          password: ${{ secrets.CR_YANDEX_TOKEN_G }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_G }}/${{secrets.DOCKER_REPO_G}}/party-party-web-app:latest
          file: Dockerfile.prod
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_G }}
          username: ${{ secrets.HOST_USERNAME_G }}
          key: ${{ secrets.SSH_KEY_G }}
          script: |
            sudo docker stop party-party-web-app
            sudo docker rm party-party-web-app
            sudo docker pull ${{ secrets.DOCKER_REGISTRY_G }}/${{secrets.DOCKER_REPO_G}}/party-party-web-app:latest
            sudo docker run -it --rm -p 80:80 --name party-party-web-app -d ${{ secrets.DOCKER_REGISTRY_G }}/${{secrets.DOCKER_REPO_G}}/party-party-web-app:latest
