name: deploy

#on:
#  push:
#    branches:
#      - main
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      #      - name: tests should run here!
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.CR_YANDEX_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cr.yandex/${{secrets.DOCKER_REPO}}/party-party-web-app
          file: Dockerfile.prod
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            sudo docker run -it --rm -p 80:80 -d cr.yandex/${{secrets.DOCKER_REPO}}/party-party-web-app:latest
